version: "3.9"

services:
  flat-manager:
    image: nalsai/flat-manager
    build: ./src
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - ./flatman:/flat-manager
    depends_on:
      - "db"
    ports:
      - 8080:8080

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: repo
      POSTGRES_USER: flatmanager
      POSTGRES_PASSWORD: mysecretpassword
